#![allow(warnings)]

use std::env;
use std::path::PathBuf;
use std::fs::File;

// Gui
use fltk::prelude::*;
use fltk::{
  app::Sender,
  browser::MultiBrowser,
  text::{TextBuffer,TextDisplay},
  menu::MenuButton,
  button::Button,
  group::Group,
  image::SharedImage,
  input::FileInput,
  group::PackType,
  frame::Frame,
  dialog,
  dialog::{dir_chooser,file_chooser},
  enums::{Align,FrameType,Color},
  misc::Progress,
};

use url as Url;
use anyhow;
use anyhow::anyhow as ah;

use crate::dimm;
use crate::frame;
use crate::common;
use crate::common::PathBufExt;
use crate::common::WidgetExtExtra;
use crate::log;
use crate::db;
use crate::lib::download;
use crate::lib::svg;

// fetch_items() {{{
pub fn fetch_items(tx: Sender<common::Msg>, label : String) -> anyhow::Result<Vec<String>>
{
  // Ask back-end for the item files
  if let Ok(rx_gameimage) = common::gameimage_cmd(vec![
      "search"
    , "--json"
    , "gameimage.search.json"
    , &label
  ])
  {
    tx.send(common::Msg::WindDeactivate);
    let _ = rx_gameimage.recv();
    tx.send(common::Msg::WindActivate);
  } // if
  else
  {
    log!("Could not execute backend to search files");
  }; // else

  // Fetch items from db generated by backend
  let result_entry = db::search::get();

  if let Ok(entry) = result_entry
  {
    let some_items = match label.as_str()
    {
      "rom" => entry.rom,
      "bios" => entry.bios,
      "core" => entry.core,
      "keys" => entry.keys,
      _ => None
    }; // match

    if let Some(items) = some_items
    {
      return Ok(items);
    } // if
  } // if

  Err(ah!("No items found"))
} // fetch_items() }}}

// pub fn install() {{{
pub fn install(tx: Sender<common::Msg>
  , title: &str
  , label: &str
  , msg_prev: common::Msg
  , msg_curr: common::Msg
  , msg_next: common::Msg)
{
  let ret_frame_header = frame::common::frame_header(title);
  let ret_frame_footer = frame::common::frame_footer();

  let frame_header = ret_frame_header.frame.clone();
  let frame_content = ret_frame_header.frame_content.clone();
  let frame_footer = ret_frame_footer.frame.clone();

  // Set previous frame
  ret_frame_footer.btn_prev.clone().emit(tx.clone(), msg_prev);
  ret_frame_footer.btn_next.clone().emit(tx.clone(), msg_next);

  // List of the currently installed items
  let mut frame_list = MultiBrowser::default()
    .with_size(frame_content.width() - dimm::border()*3 - dimm::width_button_rec()
      , frame_content.height() - dimm::border()*2)
    .with_pos(frame_content.x() + dimm::border(), frame_content.y() + dimm::border());
  frame_list.set_frame(FrameType::BorderBox);
  frame_list.set_text_size(dimm::height_text());

  // Insert items in list of currently installed items
  let mut parent = frame_list.as_base_widget();
  let result_vec_items = fetch_items(tx.clone(), label.to_string());
  if let Ok(vec_items) = result_vec_items
  {
    for item in vec_items { frame_list.add(item.as_str()); } // for
  } // if

  // Add new item
  let clone_tx = tx.clone();
  let clone_label : String = label.to_string();
  let mut btn_add = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .right_of(&frame_list, dimm::border())
    .with_frame(FrameType::RoundedFrame)
    .with_focus(false)
    .with_svg(svg::icon_add(1.0).as_str())
    .with_color(Color::Green)
    .with_callback(move |_|
    {
      // Pick files to install
      let mut chooser = dialog::FileChooser::new("."
        , "*"
        , dialog::FileChooserType::Multi
        , "Pick one or multiple files");

      // Start dialog
      chooser.show();

      // Wait for choice(s)
      while chooser.shown() { fltk::app::wait(); } // while

      // Check if choice is valid
      if chooser.value(1).is_none()
      {
        log!("No file selected");
        return;
      } // if

      // Install files
      clone_tx.send(common::Msg::WindDeactivate);
      for idx_choice in 1..chooser.count()+1
      {
        // Fetch choice
        let str_choice = chooser.value(idx_choice).unwrap();
        // Install with backend
        if let Ok(rx_gameimage) = common::gameimage_cmd(vec!["install", &clone_label, &str_choice])
        {
          // Wait for command to finish
          let _ = rx_gameimage.recv();
        } // if
        else
        {
          log!("Failed to execute backend");
        } // else
      } // for
      clone_tx.send(common::Msg::WindActivate);
      clone_tx.send(msg_curr);
    });

  // Erase package
  let mut btn_del = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .below_of(&btn_add, dimm::border());
  btn_del.set_frame(FrameType::RoundedFrame);
  btn_del.visible_focus(false);
  btn_del.set_image(Some(fltk::image::SvgImage::from_data(svg::icon_del(1.0).as_str()).unwrap()));
  btn_del.set_color(Color::Red);
  let clone_frame_list = frame_list.clone();
  let mut clone_output_status = ret_frame_footer.output_status.clone();
  let clone_label = label.to_string();
  btn_del.set_callback(move |_|
  {
    let vec_indices = frame_list.selected_items();

    if vec_indices.len() == 0
    {
      clone_output_status.set_value("No item selected for deletion");
      clone_tx.send(msg_curr);
      return;
    } // if

    // Get items
    let vec_items : Vec<String> = vec_indices.into_iter().map(|e|{ frame_list.text(e).unwrap() }).collect();

    for item in vec_items
    {
      if let Ok(rx) = common::gameimage_cmd(vec!["install", "--remove", &clone_label, &item])
      {
        let _ = rx.recv();
      } // if
      else
      {
        log!("Could not wait for deletion of {}", item);
      }; // else
    } // for
    
    clone_tx.send(msg_curr);
  });
}
// }}}

// vim: set expandtab fdm=marker ts=2 sw=2 tw=100 et :
