FROM archlinux:latest

# Update
RUN pacman -Syy --noconfirm
RUN pacman-key --init
RUN pacman -S --noconfirm archlinux-keyring
RUN pacman -Syu --overwrite "*" --noconfirm

# Install dependencies
RUN pacman -S --noconfirm --overwrite "*" autoconf automake binutils bison debugedit fakeroot \
  file findutils flex gawk gcc gettext grep groff gzip libtool m4 make patch \
  pkgconf sed sudo texinfo which git cmake gtk3 wayland-protocols wayland dbus

# Setup rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
ENV PATH "/root/.cargo/bin:$PATH"

# Copy files
RUN mkdir /gameimage
COPY ./gui /gameimage/

# Enter src dir
WORKDIR gameimage

# Compile
RUN cd launcher && cargo build --release

# Save target folder
WORKDIR /
RUN mv /gameimage/target /target
RUN rm -rf /gameimage
