FROM ghcr.io/ruanformigoni/gameimage-launcher-dev

# Copy files
RUN mkdir /gameimage
COPY ./gui /gameimage/

# Retrieve target folder
RUN mv target /target

# Enter src dir
WORKDIR gameimage

# Compile
RUN cd launcher && cargo build --release

# Move to dist
RUN mkdir /dist
RUN cp ./target/release/launcher /dist/launcher
