FROM ghcr.io/ruanformigoni/gameimage-wizard-dev

# Copy sources
COPY ./gui /gameimage

# Enter src dir
WORKDIR /gameimage

# Retrieve pre-compiled dependencies
RUN mv /target /gameimage/target

# Compile wizard
RUN cd wizard && cargo build --release --target=x86_64-unknown-linux-musl

# Make dist
RUN mkdir /dist
RUN cp /gameimage/target/x86_64-unknown-linux-musl/release/wizard /dist
