#![allow(warnings)]

use std::env;
use std::path::PathBuf;
use std::fs::File;

// Gui
use fltk::prelude::*;
use fltk::{
  app::Sender,
  browser::HoldBrowser,
  text::{TextBuffer,TextDisplay},
  menu::MenuButton,
  button::Button,
  group::Group,
  image::SharedImage,
  input::FileInput,
  group::PackType,
  frame::Frame,
  dialog::{dir_chooser,file_chooser},
  enums::{Align,FrameType,Color},
  misc::Progress,
};

use url as Url;
use anyhow;
use anyhow::anyhow as ah;

use crate::dimm;
use crate::frame;
use crate::common;
use crate::db;
use crate::download;
use crate::svg;

// fetch_items() {{{
pub fn fetch_items(label : String) -> anyhow::Result<Vec<String>>
{
  // Ask back-end for the item files
  let cmd_result = common::gameimage_cmd(vec![
      "search".to_string()
    , "--json".to_string()
    , "gameimage.search.json".to_string()
    , label.clone()
  ]);

  // No items found
  if cmd_result.is_err()
  {
    return Err(ah!("No items found (dir not found)"));
  } // if

  // Fetch items from db generated by backend
  let result_entry = db::search::get();

  if let Ok(entry) = result_entry
  {
    let some_items = match label.as_str()
    {
      "rom" => entry.rom,
      "bios" => entry.bios,
      "core" => entry.core,
      _ => None
    }; // match

    if let Some(items) = some_items
    {
      return Ok(items);
    } // if
  } // if

  Err(ah!("No items found"))
} // fetch_items() }}}

// pub fn install() {{{
pub fn install(tx: Sender<common::Msg>
  , title: &str
  , label: &str
  , msg_prev: common::Msg
  , msg_curr: common::Msg
  , msg_next: common::Msg)
{
  let mut frame = Frame::default()
    .with_size(dimm::width(), dimm::height());
  frame.set_frame(FrameType::BorderBox);
  frame.set_type(PackType::Vertical);

  let ret_frame_header = frame::common::frame_header(title);
  let ret_frame_footer = frame::common::frame_footer();

  let frame_header = ret_frame_header.frame.clone();
  let frame_content = ret_frame_header.frame_content.clone();
  let frame_footer = ret_frame_footer.frame.clone();

  // Set previous frame
  ret_frame_footer.btn_prev.clone().emit(tx.clone(), msg_prev);
  ret_frame_footer.btn_next.clone().emit(tx.clone(), msg_next);

  // List of the currently installed items
  let mut frame_list = HoldBrowser::default()
    .with_size(frame_content.width() - dimm::border()*3 - dimm::width_button_rec()
      , frame_content.height() - dimm::border()*2)
    .with_pos(frame_content.x() + dimm::border(), frame_content.y() + dimm::border());
  frame_list.set_frame(FrameType::BorderBox);
  frame_list.set_text_size(dimm::height_text());

  // Insert items in list of currently installed items
  let mut parent = frame_list.as_base_widget();
  let result_vec_items = fetch_items(label.to_string());
  if let Ok(vec_items) = result_vec_items
  {
    for item in vec_items { frame_list.add(item.as_str()); } // for
  } // if

  // Add new item
  let mut btn_add = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .right_of(&frame_list, dimm::border());
  btn_add.set_frame(FrameType::RoundedFrame);
  btn_add.visible_focus(false);
  btn_add.set_image(Some(fltk::image::SvgImage::from_data(svg::icon_add(1.0).as_str()).unwrap()));
  btn_add.set_color(Color::Green);
  let clone_tx = tx.clone();
  let clone_label : String = label.to_string();
  btn_add.set_callback(move |_|
  {
    // Pick file to install
    let choice = file_chooser("Select the item file to install", "*", ".", false);

    // Check if choice is valid
    if choice.is_none()
    {
      println!("No file selected");
      return;
    } // if
    let str_choice = choice.unwrap();

    // Install with backend
    if let Err(e) = common::gameimage_cmd(vec![
        "install".to_string()
      , clone_label.clone()
      , str_choice
    ])
    {
      println!("Failed to execute backend with {}", e.to_string());
    } // if

    clone_tx.send(msg_curr);
  });

  // Erase package
  let mut btn_del = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .below_of(&btn_add, dimm::border());
  btn_del.set_frame(FrameType::RoundedFrame);
  btn_del.visible_focus(false);
  btn_del.set_image(Some(fltk::image::SvgImage::from_data(svg::icon_del(1.0).as_str()).unwrap()));
  btn_del.set_color(Color::Red);
  let clone_frame_list = frame_list.clone();
  let mut clone_output_status = ret_frame_footer.output_status.clone();
  let clone_label = label.to_string();
  btn_del.set_callback(move |_|
  {
    let line = frame_list.value();

    if line == 0
    {
      clone_output_status.set_value("No item selected for deletion");
      return;
    } // if

    // Get project dir
    let some_path_dir_project = db::project::dir();
    if some_path_dir_project.is_err()
    {
      clone_output_status.set_value("Failure to get project dir");
      return;
    } // if

    // Get selected text
    let some_text = clone_frame_list.text(line);
    if some_text.is_none()
    {
      clone_output_status.set_value("Could not get value to delete");
    } // if

    let path_file_target = some_path_dir_project.unwrap()
      .join(clone_label.as_str())
      .join(some_text.unwrap());

    if std::fs::remove_file(path_file_target.clone()).is_err()
    {
      clone_output_status.set_value(format!("Could not delete file {}", path_file_target.into_os_string().into_string().unwrap()).as_str());
    } // if
    
    clone_tx.send(msg_curr);
  });
}
// }}}

// vim: set expandtab fdm=marker ts=2 sw=2 tw=100 et :
