#![allow(warnings)]

use std::env;
use std::path::PathBuf;
use std::fs::File;

// Gui
use fltk::prelude::*;
use fltk::{
  app::Sender,
  browser::MultiBrowser,
  text::{TextBuffer,TextDisplay},
  menu::MenuButton,
  button::Button,
  group::Group,
  image::SharedImage,
  input::FileInput,
  group::PackType,
  frame::Frame,
  dialog,
  dialog::{dir_chooser,file_chooser},
  enums::{Align,FrameType,Color},
  misc::Progress,
};

use url as Url;
use anyhow;
use anyhow::anyhow as ah;

use crate::dimm;
use crate::frame;
use crate::common;
use crate::common::PathBufExt;
use crate::common::WidgetExtExtra;
use crate::frame::wizard;
use crate::log;
use crate::db;
use crate::download;
use crate::svg;

// pub fn name() {{{
pub fn name(tx: Sender<common::Msg>, title: &str)
{
  wizard::name::name(tx.clone()
    , title
    , common::Msg::DrawCreator
    , common::Msg::DrawRetroarchIcon);
} // }}}

// pub fn icon() {{{
pub fn icon(tx: Sender<common::Msg>, title: &str)
{
  wizard::icon::icon(tx.clone()
    , title
    , common::Msg::DrawRetroarchName
    , common::Msg::DrawRetroarchIcon
    , common::Msg::DrawRetroarchRom
  );
} // }}}

// pub fn rom() {{{
pub fn rom(tx: Sender<common::Msg>, title: &str)
{
  wizard::install::install(tx.clone()
    , title
    , "rom"
    , common::Msg::DrawRetroarchIcon
    , common::Msg::DrawRetroarchRom
    , common::Msg::DrawRetroarchCore);
} // }}}

// fetch_items() {{{
pub fn fetch_items(tx: Sender<common::Msg>
  , label : String
  , use_remote : bool) -> anyhow::Result<Vec<String>>
{
  let cmd = if use_remote
  {
    vec!["search", "--remote", "--json", "gameimage.search.json", &label ]
  }
  else
  {
    vec!["search", "--json", "gameimage.search.json", &label ]
  };

  // Ask back-end for the item files
  if let Ok(rx_gameimage) = common::gameimage_cmd(cmd)
  {
    tx.send(common::Msg::WindDeactivate);
    let _ = rx_gameimage.recv();
    tx.send(common::Msg::WindActivate);
  } // if
  else
  {
    log!("Could not execute backend to search files");
  }; // else

  // Fetch items from db generated by backend
  let result_entry = db::search::get();

  if let Ok(entry) = result_entry
  {
    let some_items = match label.as_str()
    {
      "rom" => entry.rom,
      "bios" => entry.bios,
      "core" => entry.core,
      "keys" => entry.keys,
      _ => None
    }; // match

    if let Some(items) = some_items
    {
      return Ok(items);
    } // if
  } // if

  Err(ah!("No items found"))
} // fetch_items() }}}

// pub fn core() {{{
pub fn core(tx: Sender<common::Msg>, title: &str)
{
  let ret_frame_header = frame::common::frame_header(title);
  let ret_frame_footer = frame::common::frame_footer();

  let frame_header = ret_frame_header.frame.clone();
  let frame_content = ret_frame_header.frame_content.clone();
  let frame_footer = ret_frame_footer.frame.clone();

  // Set previous frame
  ret_frame_footer.btn_prev.clone().emit(tx.clone(), common::Msg::DrawRetroarchRom);
  ret_frame_footer.btn_next.clone().emit(tx.clone(), common::Msg::DrawRetroarchBios);

  // List of the currently installed items
  let mut frame_list_installed = MultiBrowser::default()
    .with_size(frame_content.width() - dimm::border()*3 - dimm::width_button_rec()
      , frame_content.height() / 2 - (dimm::border() as f32 * 1.5) as i32)
    .with_frame(FrameType::BorderBox)
    .top_left_of(&frame_content, 0)
    .with_border(dimm::border(), dimm::border());
  frame_list_installed.set_text_size(dimm::height_text());

  // Insert items in list of currently installed items
  let mut parent = frame_list_installed.as_base_widget();
  let result_vec_items = fetch_items(tx.clone(), "core".to_string(), false);
  if let Ok(vec_items) = result_vec_items
  {
    for item in vec_items { frame_list_installed.add(item.as_str()); } // for
  } // if

  // Add new item from file manager
  let clone_tx = tx.clone();
  let clone_label : String = "core".to_string();
  let btn_add = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .right_of(&frame_list_installed, dimm::border())
    .with_frame(FrameType::RoundedFrame)
    .with_focus(false)
    .with_svg(svg::icon_folder(1.0).as_str())
    .with_color(Color::Green)
    .with_callback (move |_|
    {
      // Pick files to install
      let mut chooser = dialog::FileChooser::new("."
        , "*"
        , dialog::FileChooserType::Multi
        , "Pick one or multiple files");

      // Start dialog
      chooser.show();

      // Wait for choice(s)
      while chooser.shown() { fltk::app::wait(); } // while

      // Check if choice is valid
      if chooser.value(1).is_none()
      {
        log!("No file selected");
        return;
      } // if

      // Install files
      clone_tx.send(common::Msg::WindDeactivate);
      for idx_choice in 1..chooser.count()+1
      {
        // Fetch choice
        let str_choice = chooser.value(idx_choice).unwrap();
        // Install with backend
        if let Ok(rx_gameimage) = common::gameimage_cmd(vec!["install", &clone_label, &str_choice])
        {
          // Wait for command to finish
          let _ = rx_gameimage.recv();
        } // if
        else
        {
          log!("Failed to execute backend");
        } // else
      } // for
      clone_tx.send(common::Msg::WindActivate);
      clone_tx.send(common::Msg::DrawRetroarchCore);
    });

  // Erase package
  let clone_frame_list_installed = frame_list_installed.clone();
  let mut clone_output_status = ret_frame_footer.output_status.clone();
  let clone_label = "core".to_string();
  let btn_del = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .below_of(&btn_add, dimm::border())
    .with_frame(FrameType::RoundedFrame)
    .with_focus(false)
    .with_svg(svg::icon_del(1.0).as_str())
    .with_color(Color::Red)
    .with_callback(move |_|
    {
      let vec_indices = clone_frame_list_installed.selected_items();

      if vec_indices.len() == 0
      {
        clone_output_status.set_value("No item selected for deletion");
        clone_tx.send(common::Msg::DrawRetroarchCore);
        return;
      } // if

      // Get items
      let vec_items : Vec<String> = vec_indices.into_iter().map(|e|{ clone_frame_list_installed.text(e).unwrap() }).collect();

      for item in vec_items
      {
        if let Ok(rx) = common::gameimage_cmd(vec!["install", "--remove", &clone_label, &item])
        {
          let _ = rx.recv();
        } // if
        else
        {
          log!("Could not wait for deletion of {}", item);
        }; // else
      } // for
      
      clone_tx.send(common::Msg::DrawRetroarchCore);
    });

  // List of items to install
  let mut frame_list_remote = MultiBrowser::default()
    .with_size_of(&frame_list_installed)
    .below_of(&frame_list_installed, dimm::border())
    .with_frame(FrameType::BorderBox);
  frame_list_remote.set_text_size(dimm::height_text());

  // Insert remote items in list
  let mut parent = frame_list_remote.as_base_widget();
  let result_vec_items = fetch_items(tx.clone(), "core".to_string(), true);
  if let Ok(vec_items) = result_vec_items
  {
    for item in vec_items { frame_list_remote.add(item.as_str()); } // for
  } // if

  // Add new item from remote
  let clone_tx = tx.clone();
  let clone_label : String = "core".to_string();
  let clone_frame_list_remote = frame_list_remote.clone();
  let btn_add = Button::default()
    .with_size(dimm::width_button_rec(), dimm::height_button_rec())
    .right_of(&frame_list_remote, dimm::border())
    .with_frame(FrameType::RoundedFrame)
    .with_focus(false)
    .with_svg(svg::icon_install(1.0).as_str())
    .with_color(Color::Green)
    .with_callback(move |_|
    {
      // Install files
      clone_tx.send(common::Msg::WindDeactivate);
      let clone_frame_list_remote = clone_frame_list_remote.clone();
      let clone_label = clone_label.clone();
      std::thread::spawn(move ||
      {
        for idx_item in clone_frame_list_remote.selected_items()
        {
          // Fetch choice
          let str_choice = clone_frame_list_remote.text(idx_item).unwrap();
          // Install with backend
          if let Ok(rx_gameimage) = common::gameimage_cmd(vec!["install", "--remote", &clone_label, &str_choice])
          {
            // Wait for command to finish
            let _ = rx_gameimage.recv();
          } // if
          else
          {
            log!("Failed to execute backend");
          } // else
        } // for
        clone_tx.send(common::Msg::WindActivate);
        clone_tx.send(common::Msg::DrawRetroarchCore);
      });
    });
} // }}}

// pub fn bios() {{{
pub fn bios(tx: Sender<common::Msg>, title: &str)
{
  wizard::install::install(tx.clone()
    , title
    , "bios"
    , common::Msg::DrawRetroarchCore
    , common::Msg::DrawRetroarchBios
    , common::Msg::DrawRetroarchTest);
} // }}}

// pub fn test() {{{
pub fn test(tx: Sender<common::Msg>, title: &str)
{
  wizard::test::test(tx.clone()
    , title
    , common::Msg::DrawRetroarchBios
    , common::Msg::DrawRetroarchTest
    , common::Msg::DrawRetroarchCompress);
} // }}}

// pub fn compress() {{{
pub fn compress(tx: Sender<common::Msg>, title: &str)
{
  wizard::compress::compress(tx.clone()
    , title
    , common::Msg::DrawRetroarchTest
    , common::Msg::DrawRetroarchCompress
    , common::Msg::DrawCreator);
} // }}}

// vim: set expandtab fdm=marker ts=2 sw=2 tw=100 et :
